---
title: "Untitled"
author: "Nicole Ayala"
date: "`r Sys.Date()`"
output: 
    html_document:
      toc: TRUE
      toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      Warning = FALSE, 
                      message=FALSE, 
                      fig.path = "../Output/")
```
### Organizing the Data & Loading the Libraries
```{r}
### Loading in the Libraries ###
library(tidyverse)
library(tidytuesdayR)
library(svglite)
library(colorspace)
library(here)
library(geojsonio)
library(sf)
library(ggplot2)
library(broom) 
library(rgeos)
library(scico)


### Loading the Data ###

public <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-10/PFW_2021_public.csv')

### Wrangling the Data ###
df <- public %>% 
  filter(Year == 2020) %>% # only want year 2020
  group_by(Year, subnational1_code) %>%  # grouping state w/ year
  summarise(count = n_distinct(species_code)) %>% # counting number of distinct bird species in each state
  ungroup() %>% # fixing the group by filtering out unnecessary data
  filter(grepl("US-", subnational1_code)) %>% # looking for matches with US- only, no CA-
  mutate(state = gsub("US-", "", subnational1_code)) %>% # need to change the state names (global substitutions)
  mutate(state = state.name[match(state, state.abb)]) %>% # need to match state name with actual abbreviation
  mutate(state = replace(state, subnational1_code == "US-DC", "District of Columbia")) # specific example would be D.C. in the US

## Last Filtering Attempt for Bird DF Total ###
df_total <- public %>% # piping to same filters as previously done
  filter(Year == 2020) %>% # only want year 2020
  filter(grepl("US-", subnational1_code)) %>% # need to make all the data follow US- format, ignore the rest of the data
  summarise(count = n_distinct(species_code)) # counting distinct species of birds
  
### Time to Make the Honey Comb/Hexagon Shaped US ###
hex_states <- geojson_read("https://raw.githubusercontent.com/holtzy/R-graph-gallery/master/DATA/us_states_hexgrid.geojson.json", what = "sp") # used what I found on the web for the hexagon shapes


hex_states@data = hex_states@data %>% # pipe to itself
  mutate(google_name = gsub(" \\(United States\\)", "", google_name)) # learned this from andrew hill @ carto.com, adds the abbreviations for each state


hex_states_new <- tidy(hex_states, region = "google_name") # creating a data frame with google's abbreviations of US states to make it more accurate

### I was struggling with the left join so I let it be, I think it worked out ###
df_states <- hex_states_new %>% 
  left_join(. , df, by = c("id" = "state")) %>%  # doing a left join of state name being defined within a hexagon, matching it to id data
  mutate(id = state.abb[match(id, state.name)]) #matching state name to state abbreviation
  
# fixing up DC data (state abbreviation for VA)
df_states$id[df_states$group == "District of Columbia.1"] <- "DC"

### Ensuring Labels are Correctly Formatted for States ###
labels <- cbind.data.frame(data.frame(gCentroid(hex_states, byid = TRUE), id = hex_states@data$iso3166_2))

# final left join to join id to states, ensuring abbreviations match up with id in the data 
df_total <- df_states %>% 
  left_join(. , labels, by = "id")
```
### Time to Plot

```{r}
df_total %>% 
  ggplot () +
  geom_polygon(aes(x = long, # x axis
                   y = lat,  # y axis
                   group = group, # NEVER FORGET THIS
                   fill = count), # fill is equal tot he count
                   color="plum3",  # color of the map
                   linewidth = 0.5) + # small font size
  scale_fill_scico(palette = "devon", direction = 1) +
  coord_map(clip = "on") +
  geom_text(aes(x = x, # x axis
                y = y, # y axis
                label = id, # ids are in the hexagons
                color = count <= 80),  # only count up to 60 
                size = 3, # text will be size 3
                show.legend = FALSE) + # dont want the legend
  scale_color_manual(values = c("darkolivegreen", "white")) +
  scale_y_continuous(limits = c(25, 57))+ # limits for the y axis
  annotate(geom = "text", # basically just guestimating how big the text should be for each state
           x = -136, 
           y = 37, 
           label = "6 bird species in  Hawaii ", # included a label on HI and TX
           hjust = "left",
           size = 3, 
           color = "black") +
  annotate(geom = "segment", 
           x = -136,
           y = 35, 
           xend = -136, 
           yend = 33, 
           size = 0.4,  
           arrow = arrow(length = unit(1.5, "mm")),
           color = "black") +
  annotate(geom = "text", 
           x = -122, 
           y = 27,
           label = "139 bird species in Texas", # second label for TX
           hjust = "left", 
           size = 3, 
           color = "black") +
  annotate(geom = "segment", 
           x = -116, 
           y = 28.5, 
           xend = -113, 
           yend = 28.5, 
           size = 0.4,  
           arrow = arrow(length = unit(1.5, "mm")), 
           color = "black") +
  theme_minimal() + # simple theme, light gridlines
  theme(plot.title = element_text(size = 10, 
                                  hjust = 0.5,
                                  face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(size = 8, 
                                     hjust = 0.5,
                                     lineheight = 1.1),
        plot.caption.position = "plot",
        plot.caption = element_text(size = 8, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = c(0.5, 0.85),
        legend.direction = "horizontal", # cute little legend with the gradient depicting the amount fo birds in each state
        legend.title = element_blank(), # not tile for legend
        legend.text = element_text(size = 8, # size for legend
                                   color = "black"),
        legend.key.height = unit(0.25, 'cm'), # standard height for elgend
        legend.key.width = unit(1.25, 'cm'), #standard width for legend key
        plot.margin = unit(c(0, 0.25, 0, 0.25), "cm"), # margins are standard
        plot.background = element_rect(color = "cornsilk", fill = "cornsilk")) + # background color
  labs(title = "Analysis of the Amount of Bird Species Within Each State in the United States",
       subtitle = "The total number of bird species seen in 2021 within the US by state",
       caption = "Thank you to Ryan Hart & Andrew Hill for having resources when using/loading in the hexabin plot design | NAA | Tidy Tuesday 7")

### SAVE THE PLOT ###

ggsave(here("Seventh Tidy Tuesday","Output","7thTidyTuesdayBirdsPlot.png"),# names and saves ggplot
       width = 20, height = 15)# adjust size of graph in inches
```
